rapidsai/pre-commit-hooks

test/rapids_pre_commit_hooks/test_lint.py

Use the context manager in the fixture, rather than the test, to
ensure it is automatically torn down when the test is over.

Fix test fixtures to auto-teardown

---

src/rapids_pre_commit_hooks/lint.py
src/rapids_pre_commit_hooks/shell/__init__.py
src/rapids_pre_commit_hooks/shell/verify_conda_yes.py
test/rapids_pre_commit_hooks/test_lint.py

Separate argument creation from execution. This will allow us to access the list of files before any checks are run on them.

Refactor main API

---

.pre-commit-hooks.yaml
ci/build-test.sh
pyproject.toml
src/rapids_pre_commit_hooks/copyright.py
src/rapids_pre_commit_hooks/lint.py
test/rapids_pre_commit_hooks/test_copyright.py

Fixes: https://github.com/rapidsai/pre-commit-hooks/issues/2

Add copyright check

---

src/rapids_pre_commit_hooks/copyright.py
test/rapids_pre_commit_hooks/test_copyright.py

The behavior of `--batch` mode is not consistent with the default PR mode in terms of determining whether or not a file has been modified, and that creates problems when trying to use `--batch` mode followed by PR mode. The approach of "eventual consistency" seems good enough for now.

Remove --batch mode from verify-copyright

---

src/rapids_pre_commit_hooks/copyright.py
test/rapids_pre_commit_hooks/test_copyright.py

If upstream is a user's fork that doesn't get updated, we want to instead use the local branch, which is more likely to be up to date.
Fixes: https://github.com/rapidsai/pre-commit-hooks/issues/32

Use local branch if newer than remote branch

---

.pre-commit-hooks.yaml
pyproject.toml
src/rapids_pre_commit_hooks/pyproject_license.py
test/rapids_pre_commit_hooks/test_pyproject_license.py

Add verify-pyproject-license hook

---

src/rapids_pre_commit_hooks/copyright.py

`NoSuchBranchWarning` and `ConflictingFilesError` in the copyright hook appear to be unused.
This proposes removing them.

remove unused warning and exception classes in copyright hook

---

src/rapids_pre_commit_hooks/alpha_spec.py
test/rapids_pre_commit_hooks/test_alpha_spec.py

Conda and requirements.txt allow some requirements that are not valid in a pyproject.toml. Skip over these when doing the check.

Skip checking invalid requirements

---

src/rapids_pre_commit_hooks/alpha_spec.py
test/rapids_pre_commit_hooks/test_alpha_spec.py

`dependencies.yaml` uses aliases fairly extensively, and we want to properly account for them when checking for alpha specs. If multiple nodes point to the same anchor through an alias, only issue the correction on one of them, and include the anchor name in the correction.

Account for aliases in alpha spec check

---

.pre-commit-hooks.yaml
ci/build-test.sh
pyproject.toml
src/rapids_pre_commit_hooks/alpha_spec.py
test/rapids_pre_commit_hooks/test_alpha_spec.py

rapids-metadata was created so that we wouldn't have to cut a new pre-commit-hooks release every time the structure of RAPIDS changes. Use rapids-metadata and get rid of the baked-in list of packages.

Use rapids-metadata

---

.pre-commit-hooks.yaml
pyproject.toml

Only verify-alpha-spec depends on rapids-metadata right now, so make it an optional dependency list to avoid having to pass the RAPIDS nightly repo for every hook.

Factor out dependencies for verify-alpha-spec

---

.pre-commit-config.yaml
pyproject.toml
test/examples/verify-alpha-spec/fail/master/dependencies.yaml
test/examples/verify-alpha-spec/pass/master/dependencies.yaml
test/examples/verify-conda-yes/fail/master/test.sh
test/examples/verify-conda-yes/pass/master/test.sh
test/examples/verify-copyright/fail/branch/test.py
test/examples/verify-copyright/fail/master/test.py
test/examples/verify-copyright/pass/branch/test.py
test/examples/verify-copyright/pass/master/test.py
test/examples/verify-pyproject-license/fail/master/pyproject.toml
test/examples/verify-pyproject-license/pass/master/pyproject.toml
test/test_hooks.py
test/test_pre_commit.py

Dependency issues in .pre-commit-hooks.yaml previously caused hooks other than verify-alpha-spec to fail to install. Add an integration test where we actually run pre-commit with every hook to avoid such issues in the future.

Add integration test for running pre-commit

---

src/rapids_pre_commit_hooks/alpha_spec.py
test/rapids_pre_commit_hooks/test_alpha_spec.py

Projects that don't use RAPIDS version conventions should still be able to depend on RAPIDS packages. Add a --rapids-version argument to verify-alpha-spec so that the hook can still be used.
Closes #43

Add --rapids-version argument to verify-alpha-spec

---

src/rapids_pre_commit_hooks/alpha_spec.py
test/rapids_pre_commit_hooks/test_alpha_spec.py

We already accounted for anchors on individual packages, but it was discovered that kvikio has anchors on package lists. Account for this scenario too. If we ever find anchors at another level, we can propagate the anchor checking to every level of the stack.

Account for anchors on package lists

---

src/rapids_pre_commit_hooks/copyright.py
src/rapids_pre_commit_hooks/lint.py

`typing.Callable` has been deprecated since Python 3.9. Switch to `collections.abc.Callable`. Also switch to `collections.abc.Generator` and `collections.abc.Iterable`.

Use collections.abc.Callable instead of typing.Callable

---

.github/workflows/run-tests.yaml
pyproject.toml
src/rapids_pre_commit_hooks/copyright.py
src/rapids_pre_commit_hooks/lint.py
test/rapids_pre_commit_hooks/test_copyright.py

Also proposes requiring Python 3.10, since https://github.com/rapidsai/build-planning/issues/88 is being rolled out.
Fixes https://github.com/rapidsai/pre-commit-hooks/issues/48

Display notice when copyrighted file is copied or renamed

---

.pre-commit-config.yaml
src/rapids_pre_commit_hooks/alpha_spec.py
src/rapids_pre_commit_hooks/copyright.py
src/rapids_pre_commit_hooks/lint.py
test/rapids_pre_commit_hooks/test_alpha_spec.py
test/rapids_pre_commit_hooks/test_copyright.py
test/rapids_pre_commit_hooks/test_lint.py
test/test_pre_commit.py

This project has `requires-python = ">= 3.10"`, but is telling `pyupgrade` it supports Python `>= 3.8`. This PR proposes the following:
* fixing that by passing `--py310-plus` to `pyupgrade`
* upgrading all `pre-commit` hooks to their latest versions (since I'm touching that file anyway)
All other changes in the diff were made automatically by the `pre-commit` hooks as a result of those 2 changes.

upgrade pyupgrade target version to Python 3.10, upgrade pre-commit hooks

---

src/rapids_pre_commit_hooks/copyright.py
test/test_pre_commit.py

The copyright test uses the current date, rather than the file modification date. Mock the current date in the pre-commit test.

Fix copyright year in pre-commit test

---

.pre-commit-hooks.yaml
pyproject.toml
src/rapids_pre_commit_hooks/codeowners.py
test/examples/verify-codeowners/fail/master/.github/CODEOWNERS
test/examples/verify-codeowners/pass/master/.github/CODEOWNERS
test/rapids_pre_commit_hooks/test_codeowners.py
test/test_pre_commit.py

Add verify-codeowners hook

---

src/rapids_pre_commit_hooks/codeowners.py
test/rapids_pre_commit_hooks/test_codeowners.py

Also use the `after` argument in `required_codeowners_list()`, which wasn't being used before.

Make codeowners rules optional by group

---

tests/examples/verify-codeowners/fail/metadata.yaml
tests/examples/verify-codeowners/pass/metadata.yaml
tests/test_pre_commit.py

Instead of storing test metadata in the Python code, store it in a `metadata.yaml` file in the test directory.

Add `metadata.yaml` to pre-commit tests

---

pyproject.toml
src/rapids_pre_commit_hooks/alpha_spec.py
tests/rapids_pre_commit_hooks/test_alpha_spec.py

This will allow us to more easily support projects like ucxx, which use a different versioning scheme but still store their RAPIDS version in a separate file.

Add `--rapids-version-file` argument to `verify-alpha-spec`
